### PR TITLE
Feat-fro-2-5-Update-sideBar

### PR DESCRIPTION
**Pull request by christofa**

### CODE REVIEW

**Review by jaydhales — COMMENTED** [review]
/admin/info scss was deleled, why?

**Comment by christofa** [comment]
It was my old file. there was nothing tangible inside

**Comment by christofa** [comment]
It was my old file. there was nothing tangible inside

**Comment by christofa** [comment]
It was my old file. there was nothing tangible inside

**Review by jaydhales — APPROVED** [review]

**Pull request merged**
